{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-gapps-ingress
  labels:
    app.kubernetes.io/name: gapps
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    # Security Headers
    nginx.ingress.kubernetes.io/proxy-body-size: 2500m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 12k
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options SAMEORIGIN always";
      more_set_headers "X-XSS-Protection 1; mode=block";
      more_set_headers "Strict-Transport-Security 'max-age=31536000; includeSubDomains; preload'";
      more_set_headers "X-Content-Type-Options nosniff";
      more_set_headers "Referrer-Policy strict-origin";
      more_set_headers "Feature-Policy geolocation 'none';midi 'none';sync-xhr 'none';microphone 'none';camera 'none';magnetometer 'none';gyroscope 'none';fullscreen 'self';payment 'none';";
      more_set_headers "Permissions-Policy geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()";
      more_set_headers "server_tokens off;";
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}  # Use the host value from values.yaml
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.backendServiceName }}
                port:
                  number: {{ .Values.ingress.backendServicePort }}
  # tls:
  #   - hosts:
  #       - host: example-tls  # Use the host value from values.yaml
  #     secretName: {{ .Values.ingress.tlsSecretName }}
{{- end }}