{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  username: {{ .Values.postgres.credentials.username }}
  password: {{ .Values.postgres.credentials.password }}
{{- end }}
